Rothamsted/knetminer

- arabidopsis/client/src/main/webapp/html/release.html
- barley/client/src/main/webapp/WEB-INF/tags/layout/footer.tag
- barley/client/src/main/webapp/html/release.html
- chicken/client/src/main/webapp/html/release.html
- common/client/src/main/webapp/WEB-INF/tags/layout/footer.tag
- cow/client/src/main/webapp/html/release.html
- pig/client/src/main/webapp/html/release.html
- poplar/client/src/main/webapp/html/release.html
- potato/client/src/main/webapp/WEB-INF/tags/layout/footer.tag
- potato/client/src/main/webapp/html/release.html
- rice/client/src/main/webapp/WEB-INF/tags/layout/footer.tag
- rice/client/src/main/webapp/html/release.html
- tomato/client/src/main/webapp/WEB-INF/tags/layout/footer.tag
- tomato/client/src/main/webapp/html/release.html
- wheat/client/src/main/webapp/html/release.html
BBSRC Logo updated for footer.tag (in common, barley, potato, rice,
tomato) and release.html pages (in arabidopsis, barley, chicken, cow,
pig, poplar, potato, rice, tomato, wheat).
> BBSRC Logo updated

- pom.xml
QTLnm_master_POM_updated cicer instance added as MVN module
> QTLnm_master_POM_updated cicer added

- arabidopsis/client/src/main/webapp/html/data/sampleQuery.xml
- arabidopsis/server/src/main/resources/SemanticMotifs.txt
- common/server/src/main/java/rres/ondex/server/ClientWorker.java
- common/server/src/main/java/rres/ondex/server/OndexServiceProvider.java
- common/server/src/main/java/rres/ondex/server/QTL.java
This might cause some compatibility issues with older networks and we encourage to recreate the networks using the latest version of the Fasta-GFF3 parser.
> Changed data type of Chromosome attribute from Integer to String

- common/client/src/main/webapp/html/KnetMaps/javascript/knet-container.js
- common/client/src/main/webapp/html/css/style.css
KnetMaps and legend cleaned_up and updated
> knetmaps container and legend modified

- common/client/src/main/webapp/html/javascript/utils.js
- common/server/src/main/java/rres/ondex/server/ClientWorker.java
- common/server/src/main/java/rres/ondex/server/OndexServiceProvider.java
removed from evidencepath-oxl and network-oxl
> oxl removed to have only json generated for network view

- common/client-base/src/main/webapp/html/KnetMaps/config/url_mappings.js
- common/client-base/src/main/webapp/html/KnetMaps/javascript/knet-itemInfo.js
- common/server-datasource-api/src/main/java/rres/knetminer/datasource/api/QTL.java
- common/server-datasource-ondexlocal/src/main/java/rres/knetminer/datasource/ondexlocal/OndexLocalDataSource.java
- common/server-datasource-ondexlocal/src/main/java/rres/knetminer/datasource/ondexlocal/OndexServiceProvider.java
- restrict Genomaps XML to user geneList (if provided)
- fix QTL filter issues, for user-defined QTL region
- KnetMaps add PMID url in ItemInfo for relation attributes
this commit addresses a few of these issues:  #138
> Gene List restriction, QTL filter, KnetMaps (relation attr. urls)

- common/client-base/src/main/webapp/html/javascript/utils.js
- common/server-datasource-ondexlocal/src/main/java/rres/knetminer/datasource/ondexlocal/OndexLocalDataSource.java
- common/server-datasource-ondexlocal/src/main/java/rres/knetminer/datasource/ondexlocal/OndexServiceProvider.java
non-wheat SNP bug fixed as well, for Genomaps
> restrict Genomaps view to user geneList

- common/server-base/src/main/webapp/WEB-INF/views/genepage.jsp
added url explicitly in genepage JSP (for now)
> api_url tweak for ws Wheat genepage endpoint

- common/server-datasource-ondexlocal/src/main/java/rres/knetminer/datasource/ondexlocal/OndexServiceProvider.java
fixing geneTable accidentally omitted line-breaks
> Ara pub filter

- common/quickstart/Dockerfile
- common/quickstart/Dockerfile-dev
- common/quickstart/Dockerfile-local
- common/quickstart/client/src/main/webapp/html/javascript/utils-config.js.template
- common/server-base/src/main/webapp/WEB-INF/views/evidencepage.jsp
- common/server-base/src/main/webapp/WEB-INF/views/genepage.jsp
- all 3 dockerfiles - added npm unsafe-perm true
- changed knetmaps dist js and css dep's to https for both server-base/WEB-INF/views (jsp)
- change api_url to relative, i.e., "../ws/!!LINKNAME!!";
> Knetminer 3.0 changes to api_url, plus dockerfiles/genepage tweaked

- common/aratiny/aratiny-ws/src/main/webapp/WEB-INF/web.xml
- common/aratiny/aratiny-ws/src/test/resources/jetty-web.xml
- common/aratiny/aratiny-ws/src/test/resources/knetminer-config/data-source.xml
> fix URI resolution for config files and jetty web

- common/client-base/src/main/webapp/html/javascript/utils.js
fix for https://github.com/Rothamsted/knetminer/issues/355 bug
> issue #355 bug fix

- common/client-base/src/main/webapp/html/GeneView/summariseLegend.js
fixed conceptType counts error/incorrect in GeneView legend
> issue #375 fix GeneView legend

- common/client-base/src/main/webapp/WEB-INF/tags/layout/page.tag
- common/client-base/src/main/webapp/html/GeneView/summariseLegend.js
- common/client-base/src/main/webapp/html/css/style.css
- common/client-base/src/main/webapp/html/javascript/evidence_legend.js
- common/client-base/src/main/webapp/html/javascript/utils.js
>  req #373 interactive legend (filter) for EvidenceView

- common/client-base/src/main/webapp/html/css/style.css
- common/server-base/src/main/webapp/WEB-INF/views/evidencepage.jsp
- common/server-base/src/main/webapp/WEB-INF/views/genepage.jsp
- common/server-datasource-ondexlocal/src/main/java/rres/knetminer/datasource/ondexlocal/OndexServiceProvider.java
> fixes to #371 #374 #311

- common/server-datasource-ondexlocal/src/main/java/rres/knetminer/datasource/ondexlocal/OndexServiceProvider.java
> removeOldAttributesFromKBGraph - attVisible null fix

- common/client-base/src/main/webapp/html/KnetMaps/css/knet-style.css
- common/client-base/src/main/webapp/html/KnetMaps/javascript/knet-conceptsLegend.js
- common/client-base/src/main/webapp/html/javascript/releaseNotes/showNetworkStats.js
- common/server-datasource-ondexlocal/src/main/java/rres/knetminer/datasource/ondexlocal/OndexServiceProvider.java
Example image:
Icons will be faded if user cannot add more concepts, and return to normal if adding concepts again.
May be worth adding a button to reset all concepts to full opacity, for when a user wants to take screenshots.
> New legend feature

- common/client-base/src/main/webapp/html/KnetMaps/css/knet-style.css
- common/client-base/src/main/webapp/html/KnetMaps/javascript/knet-conceptsLegend.js
- common/client-base/src/main/webapp/html/javascript/releaseNotes/showNetworkStats.js
- common/server-datasource-ondexlocal/src/main/java/rres/knetminer/datasource/ondexlocal/OndexServiceProvider.java
Reverts Rothamsted/knetminer#431
**Note*** Further testing on certain datasets revealed strange HTML injection & rendering issues not present on other datasets & aratiny. Counts are also suspicious - needs further testing.
> Revert "New legend feature"

- common/client-base/src/main/webapp/WEB-INF/tags/layout/footer.tag
> footer tidy up

- common/client-base/src/main/webapp/html/KnetMaps/javascript/knet-menu.js
- common/server-base/src/main/webapp/WEB-INF/views/evidencepage.jsp
- common/server-base/src/main/webapp/WEB-INF/views/genepage.jsp
- and 6x image/thumbnail scaling
> knetmaps invocation changes

- common/client-base/src/main/webapp/html/KnetMaps/javascript/knet-menu.js
- common/client-base/src/main/webapp/html/javascript/utils.js
- common/server-datasource-ondexlocal/src/main/java/rres/knetminer/datasource/ondexlocal/OndexServiceProvider.java
Note:
- in client-base/src/main/webapp/html/KnetMaps/javascript/knet-menu.js - see L50 onwards for saveJSON code and tests with backend summary_json (dbVersion, etc - fails) and auth get and api/v1/networks POST (L77 onwards), plus dateFormat change
- dateFormat also edited in back-end json, at common/server-datasource-ondexlocal/src/main/java/rres/knetminer/datasource/ondexlocal/OndexServiceProvider.java
- utils.js (commented out failed attempt to connect babvs72 knetspace from local aratiny)
> knetmaps save json (partial fix)

- common/client-base/src/main/webapp/html/KnetMaps/javascript/knet-menu.js
- with exportJson fix by Terry,
- also added more knetMetadata json params (numNodes, numEdges, etc.) to Post (besides graph, image), 
- ToDo: add backend api metadata (like dbVersion, provider) to json and stringify (need to fix that $.get retrieval 1st,
- ToDo: test POST new knetwork instead of patch existing network-id.
> exportJson fix by Terry

- common/client-base/src/main/webapp/html/KnetMaps/javascript/knet-menu.js
- common/client-base/src/main/webapp/html/KnetMaps/javascript/knetmaps.js
also added apiGraphSummary null check
> knet-menu pass networkId

- common/client-base/src/main/webapp/html/javascript/saveKnetwork/save-knet.js
- common/server-base/src/main/webapp/static/js/saveKnetwork/save-knet.js
to render centered on both UI client and genepage api, fyi
> fix knet-save upload jbox positon x,y

- common/client-base/src/main/webapp/html/KnetMaps/config/url_mappings.js
added new entries- ENSEMBL-PLANTS and REACTOME and their urls
> knetmaps infobox url mappings

- species/barley/maven-settings.xml
- species/tomato/maven-settings.xml
tomato and barley maven-settings
> updated tomato and barley missing settings

- client-base/src/main/webapp/html/javascript/utils.js
https://github.com/Rothamsted/knetminer/issues/570 feature from issue #570 added
> feature from issue #570 added

- aratiny/aratiny-client/src/main/webapp/html/release.html
aratiny-client release html logo url edited
> update release page logo url

- aratiny/aratiny-client/pom.xml
- aratiny/aratiny-client/src/main/webapp/WEB-INF/urlrewrite.xml
- aratiny/aratiny-client/src/main/webapp/WEB-INF/web.xml
- aratiny/aratiny-client/src/main/webapp/html/genepage.jsp
- aratiny/aratiny-client/src/main/webapp/html/javascript/utils-config.js
- client-base/pom.xml
- client-base/src/main/webapp/WEB-INF/tags/layout/content.tag
- client-base/src/main/webapp/WEB-INF/tags/layout/genepage.tag
- client-base/src/main/webapp/WEB-INF/tags/layout/network-view.tag
- client-base/src/main/webapp/html/css/genepage.css
- client-base/src/main/webapp/html/javascript/genepage.js
- client-base/src/main/webapp/html/javascript/multispecies.js
This pull request contains the following changes. 
- Replaced genePage.java servlet class  with urlrewritefilter module to route resource to '/genepage.'
- Created `network-view.tag` layout component to use within the content.tag tab view and genepage.tag content section
- Temporary solution to detect service API  accurately. 
- minor fix in multispecies.Js
> #659 Refined genepage view
